### ISSUE TITLE
writing characters beyond ASCII

### ISSUE THREAD

**Issue by dwbruhn** [ericnorris/node-cdb#3]
First, thank you for making available what appears to be the only node module for writing cdb files!

I'm having some trouble with writing/reading characters beyond ASCII.

Here's my code for writing two values to the same key, the first being in Chinese:

```
var cdb = require('constant-db');
var writer = new cdb.writable('./test.cdb');
writer.open(function (err) {
    if (err) {
        throw err;
    }
    writer.put('myKey', '你好');
    writer.put('myKey', 'test value!');
    writer.close(function (err) {
        if (err) {
            throw err;
        }
    });
});
```

And here's my code for reading the values:

```
var cdb = require('constant-db');
var reader = new cdb.readable('./test.cdb');
reader.open(function (err) {
    if (err) {
        throw err;
    }
    reader.get('myKey', function (err, data) {
        if (err) {
            throw err;
        }
        console.log(data);
        var buf = new Buffer(data);
        console.log(buf.toString('utf8'));

        reader.getNext(function (err, data) {
            if (err) {
                throw err;
            }
            console.log(data);
            var buf = new Buffer(data);
            console.log(buf.toString('utf8'));

            reader.close(function (err) {
                if (err) {
                    throw err;
                }
            });
        });
    });
});
```

And here's the output:

```
<Buffer 00 00>

<Buffer 74 65 73 74 21>
test value!
```

Notice that the buffer for the first value is all zeroes. Am I doing something wrong, or is this a bug?

**Comment by dwbruhn** [comment]
I did a little more testing, and it appears to be a length calculation error somewhere in the code. If I write this instead:

```
writer.put('myKey', 'José 2005');
```

Then the output is:

```
<Buffer 4a 6f 73 c3 a9 20 32 30 30>
José 200
```

The _é_ is correctly encoded as UTF-8 0xc3a9, but the string is being truncated and _5_ gets chopped off the end, probably because it's expecting all characters to be one byte long.

**Comment by dwbruhn** [comment]
Here's the problem:

```
 var record = new Buffer(8 + key.length + data.length),
```

https://github.com/ericnorris/node-cdb/blob/master/src/writable-cdb.js#L56

and

```
record.writeUInt32LE(data.length, 4);
```

https://github.com/ericnorris/node-cdb/blob/master/src/writable-cdb.js#L63

data.length won't give the number of UTF-8 bytes needed to store the string.

**Comment by ericnorris** [comment]
Hey there @dwbruhn! You are correct, that seems to be exactly the issue. I had a chance to look at it earlier and I think the proper solution would be to use [Buffer.byteLength](https://nodejs.org/api/buffer.html#buffer_class_method_buffer_bytelength_string_encoding) to determine the actual byte length of the string before writing.

I'll take a deeper look and get a fix out shortly, but thank you for investigating!

**Comment by ericnorris** [comment]
This should work now in both the readable and writable modules. Reopen this if there any other cases of UTF-8 not working.
